import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react';
import styles from 'styled-jsx/css'


const defaultEndpoint = 'https://rickandmortyapi.com/api/character/';
export async function getServerSideProps(){
  const res= await fetch(defaultEndpoint);
  const data = await res.json();
  return {
  props: {
    data
  }
  }

}
export default function Home({data}) {
  const { info, results: defaultResults = [] } = data;
  const [results, updateResults] = useState(defaultResults);
  const [page, updatePage] = useState({
    ...info,
    current: defaultEndpoint
  });

  const { current } = page;

useEffect(() => {
  if ( current === defaultEndpoint ) return;

  async function request() {
    const res = await fetch(current)
    const nextData = await res.json();

    updatePage({
      current,
      ...nextData.info
    });

    if ( !nextData.info?.prev ) {
      updateResults(nextData.results);
      return;
    }

    updateResults(prev => {
      return [
        ...prev,
        ...nextData.results
      ]
    });
  }

  request();
}, [current]);

function handleLoadMore() {
  updatePage(prev => {
    return {
      ...prev,
      current: page?.next
    }
  });
}

function handleOnSubmitSearch(e) {
  e.preventDefault();

  const { currentTarget = {} } = e;
  const fields = Array.from(currentTarget?.elements);
  const fieldQuery = fields.find(field => field.name === 'query');

  const value = fieldQuery.value || '';
  const endpoint = `https://rickandmortyapi.com/api/character/?name=${value}`;

  updatePage({
    current: endpoint
  });
}
  return (
    <div className="container">
      <Head>
       
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">

        <form className="search" onSubmit={handleOnSubmitSearch}>
          <input name="query" type="search" />
          <button>Search</button>
        </form>      
       
        <ul className="grid">
            {results.map(result => {
             const { id, name, image } = result;
              return (
                <li key={id} className="card">
                    <a href="#">
                    <h3>{ name }</h3>
                  </a>
                  <img src={image} alt={`${name} Thumbnail`} />
                
                </li>
              )
            })}
          </ul>
        <p>
          <button onClick={handleLoadMore}>Load more</button>
        </p>
      </main>
      <style jsx>
        {`
        .container{
          min-height: 100vh;
          

        }
        .grid{
          list-style: none;
          margin-left: 0;
          padding-left: 0;
          display: flex;
          align-items: center;
          justify-content: center;
          flex-wrap: wrap;
          max-width: 800PX;
          margin-top: 3em;
           }
      .card{
          margin: 1rem;
          flex-basis: 45%;
          padding: 1.5rem;
          text-align: left;
          color: inherit;
          text-decoration: none;
          border: 1px solid #eaeaea;
          border-radius: 10px;
          transition: color 0.15s ease;
          border-color: 00.15s ease;
      
      }
      .logo{
          height: 1em;
      }
      @media(max-width:600px) {
       .grid{
           width: 100%;
           flex-direction: column;
       }
      
      }
      .search input {
        margin-right: .5em;
      }
      
      @media (max-width: 600px) {
        .search input {
          margin-right: 0;
          margin-bottom: .5em;
        }
      
        .search input,
        .search button {
          width: 100%;
        }
      }
        
        `}
      </style>

      <footer className="footer">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className="logo">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
